Runs with single offset irf
VERITAS-Observatory/V2DL3 pull request #152
Opened 2022-08-31 06:26 UTC by sona-patel

2022-08-31 14:21 UTC, sona-patel commented on pyV2DL3/eventdisplay/convertROOT2fits.py
> +    if not (full_enclosure) and not (point_like):
True, we have only two! 

Note: The changes in `conertROOT2fits.py` and `v2dl3_for_vegas.py` is not related to this PR. flake8 formatting was required to pass the CI test.

2022-08-31 14:22 UTC, GernotMaier commented on pyV2DL3/eventdisplay/convertROOT2fits.py
> +    if not (full_enclosure) and not (point_like):
OK, so this if statement does not make sense? Is it even possible to reach this? If not, maybe we should remove it then.

2022-08-31 14:25 UTC, sona-patel commented on pyV2DL3/eventdisplay/convertROOT2fits.py
> +    if not (full_enclosure) and not (point_like):
I think this complete file should be removed as its not used at all in the converter - #149 !

2022-08-31 14:27 UTC, GernotMaier commented on pyV2DL3/eventdisplay/convertROOT2fits.py
> +    if not (full_enclosure) and not (point_like):
Yes, please remove it - I linked #149 to this PR.

2022-08-31 14:32 UTC, GernotMaier approved these changes
All good now from my side.

2022-08-31 18:08 UTC, tobiaskleiner approved these changes

2022-11-07 06:51 UTC, GernotMaier requested changes
@sona-patel : could you clarify the relation of this branch with the `rhv_runs` branch?

2022-11-08 08:47 UTC, GernotMaier commented
This PR has been done to prepare a demonstration file for gammapy. It is superseeded and therefore closed.

2022-11-08 08:47 UTC, closed without merging